[colors]
background = '#fafafa'
foreground = '#4b505b'
selection-background = '#dde2e7'
selection-foreground = '#4b505b'
cursor = '#6996e0'
black = '#dde2e7'
red = '#d05858'
green = '#608e32'
yellow = '#be7e05'
blue = '#5079be'
magenta = '#b05ccc'
cyan = '#3a8b84'
white = '#4b505b'
light-black = '#8790a0'
light-red = '#e17373'
light-green = '#76af6f'
light-yellow = '#be7e05'
light-blue = '#6996e0'
light-magenta = '#bf75d6'
light-cyan = '#3a8b84'
light-white = '#4b505b'
