[colors]
background = '#fafafa'
foreground = '#4b505b'
selection-background = '#dde2e7'
selection-foreground = '#4b505b'
cursor = '#6996e0'
black = '#e8ebf0'
red = '#d05858'
green = '#608e32'
yellow = '#be7e05'
blue = '#5079be'
magenta = '#b05ccc'
cyan = '#3a8b84'
white = '#4b505b'
light-black = '#e8ebf0'
light-red = '#d05858'
light-green = '#608e32'
light-yellow = '#be7e05'
light-blue = '#5079be'
light-magenta = '#b05ccc'
light-cyan = '#3a8b84'
light-white = '#4b505b'
