[colors]
background = '#011627'
foreground = '#d6deeb'
selection-background = '#1d3b53'
selection-foreground = '#5f7e97'
cursor = '#80a4c2'
black = '#011627'
red = '#f78c6c'
green = '#addb67'
yellow = '#ffcb8b'
blue = '#82aaff'
magenta = '#c792ea'
cyan = '#7fdbca'
white = '#bec5d4'
light-black = '#44596b'
light-red = '#ef5350'
light-green = '#22da6e'
light-yellow = '#ffeb95'
light-blue = '#5ca7e4'
light-magenta = '#7e57c2'
light-cyan = '#21c7a8'
light-white = '#ffffff'
