[colors]
background = '#242933'
foreground = '#BBC3D4'
selection-background = '#434C5E'
selection-foreground = '#D8DEE9'
cursor = '#575279'

black = '#191D24'
red = '#BF616A'
green = '#A3BE8C'
yellow = '#EBCB8B'
blue = '#5E81AC'
magenta = '#B48EAD'
cyan = '#8FBCBB'
white = '#D8DEE9'
light-black = '#1E222A'
light-red = '#C5727A'
light-green = '#B1C89D'
light-yellow = '#EFD49F'
light-blue = '#81A1C1'
light-magenta = '#BE9DB8'
light-cyan = '#9FC6C5'
light-white = '#E5E9F0'

