[colors]
background = '#faf4ed'
foreground = '#575279'
selection-background = '#faf4ed'
selection-foreground = '#575279'
cursor = '#575279'
black = '#f2e9e1'
red = '#b4637a'
green = '#56949f'
yellow = '#ea9d34'
blue = '#286983'
magenta = '#907aa9'
cyan = '#d7827e'
white = '#575279'
light-black = '#9893a5'
light-red = '#b4637a'
light-green = '#56949f'
light-yellow = '#ea9d34'
light-blue = '#286983'
light-magenta = '#907aa9'
light-cyan = '#d7827e'
light-white = '#575279'
