[colors]
background = '#232136'
foreground = '#e0def4'
selection-background = '#232136'
selection-foreground = '#e0def4'
cursor = '#e0def4'
black = '#393552'
red = '#eb6f92'
green = '#9ccfd8'
yellow = '#f6c177'
blue = '#3e8fb0'
magenta = '#c4a7e7'
cyan = '#ea9a97'
white = '#e0def4'
light-black = '#6e6a86'
light-red = '#eb6f92'
light-green = '#9ccfd8'
light-yellow = '#f6c177'
light-blue = '#3e8fb0'
light-magenta = '#c4a7e7'
light-cyan = '#ea9a97'
light-white = '#e0def4'
