format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$cmd_duration\
$dart\
$lua\
$nodejs\
$ruby\
$rust\
$line_break\
$character"""

[character]
success_symbol = "[[♥](green) ❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[directory.substitutions]
'~/work/bitbucket/maxeda' = 'maxeda'

[docker_context]
format = 'via [🐋 $context](blue bold)'

[git_status]
format = '([$up_to_date$ahead_behind]($style) )'
style = "cyan"
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"
cherry_pick = '[🍒 PICKING](bold red)'
